site_name: Node-Crawler

pages:
  - Node-Crawler介绍: 'index.md'
  - 快速上手: 'quick_start.md'
  - 高级功能: 'extra_example.md'
  - 参数手册: 'reference/main.md'
  - 可捕获事件: 
    - 介绍: 'event/introduce.md'
    - schedule: 'event/schedule.md'
    - limiterChange: 'event/limiterChange.md'
    - request: 'event/request.md'
    - drain: 'event/drain.md'

theme: readthedocs
